language: elixir
git:
  depth: 1000
cache:
  directories:
  - _build
  - deps
services:
- docker
elixir:
- 1.6.6
otp_release:
- 21.0
notifications:
  email:
    recipients:
    - andr.savenkov@i.ua
  slack:
    rooms:
      - secure: "sNBqATKRgdI6Ir70RO2jgfBjSPpk/Qjgjstg5KtdXQKn7iSI6j5Qdor6Jiey3CU68d3e+veTdSolmLtqsWkVQyNdu+OuVoo/+Rqc4MApnJY8RrdxQfs4yzGQWPJxpWE1TIjCTC0UPC78E5joeyUnejCrw1N4lAoVPbW/F9DTR8xgVJTFWtXqxQ0SzTMJs9OYZuNBaI1uvzXUcPR9MJELVuoulqDt0yr3BeXPWMc6OblzIPJHesHKfmpqk8vDyZ7N7edcf3Q/Ao6qX7eT2l7xVJzUUqpMpyyz0BocfKShTEG5/O5HGQdLlY8n9vRzWy4KGNvNnu1zeLA4wOkRXndaLS2oA8ACqcUVx6B4KpE6/SA3tEA1hdfnq/LPV1exAPtCj7cgJ9MdU9H+iEiSHQst1twngFhR7qcEXZQsGAf8oZ1sp+CGrqC6th5Rdxij/kDFx5blWnuozZTKoz7ILBxu6Hvso6N+lNAlPQMIECXPM2Qxtw2IlEwW2Yfk3i8btF3pBe6Tal863r7QgGINeq6vgemxiZ8opQgHxnYCklsgcrU8nKsb/YJpkfVf0RT12kXOLnb4QqR60zT39HRRAR4jIQPcT9CCZIDirHTX5vO+ZyyEWDUGyM1NCP/FcVpppbrnguAFJ8Q04xLlUmtgJizGi6IxhqVmkbEdcKnFVVaWd3M="
env:
  global:
  - MIX_ENV=prod
branches:
  only:
  - devel
jobs:
  include:
  - stage: test and build
    name: Build Docker container
    script: make staging_build
