language: elixir
git:
  depth: 1000
cache:
  directories:
  - _build
  - deps
services:
- docker
elixir:
- 1.6.6
otp_release:
- 21.0
notifications:
  email:
    recipients:
      - andr.savenkov@i.ua
    on_success: always
    on_failure: always
  slack:
    rooms:
      secure: mYk5tJga1m1P83cDAi8YXxOOu2XofxwclM+EwF954XERj9hjP3Wq+vLzw25FlsNBskgqVGVy1+lOM/aP3SLosOKfhBuxA745HlpT5Oo3umJVBfBlsZY/yDKbcR6uNN0JH0h9w2U+tvmut/NmeoG8mvuRAfZhk6MelqEn25Idd/JVGFDxhfysfzNRgUhF3oy6/kkgOSuaOABMtw6rqFej6b9nWLGiw56AyOHOi5F8ADibBOVKkS0vXkCx2RRAalrp+Iu63Qkib7btkP1zYFMI4Ha99K4V1bg8Zy5bL9NYQQeKenn8im3ETYKckSbzsAywS0HOQYs7oaos9d+dQCS7Dh+1GDPFQgWHo/X3u6lmFo97+w2FRhKveaQ6BowsQ9Ps/V+1pk5CFgl7nZo5R4PIq526OBzR2nhMNgyh/B5IflmivA+TtCCVekQkI8HDl8LgHJ7qFAXtrhqZOmtwV6ZtOJPDdEiykHh0m1I5pk1L/gmnqHsCZdSg8yKEqNiScdpxXkVe1s9HOfte/JxN6cRkarDIzvM+A+e/tuy7zu+eG8iXp0D5zLC6xq6NMLIbIjggX4N4DtdOkxlzFoMAyEdh8al8KcB2pN2lguOsOt5FykhAJvvn4ytJKH49VSwAN9kiIjtXu9n/eJ0t2XV48BS6tnIO9eYMS4wWhY/UV3nCFgc=
    on_success: always
    on_failure: always
env:
  global:
  - MIX_ENV=prod
branches:
  only:
  - devel
jobs:
  include:
  - stage: test and build
    name: Build Docker container
    script: make staging_build
