language: elixir
git:
  depth: 1000
cache:
  directories:
  - _build
  - deps
services:
- docker
elixir:
- 1.6.6
otp_release:
- 21.0
notifications:
  email:
    recipients:
      - andr.savenkov@i.ua
    on_success: always
    on_failure: always
  slack:
    rooms:
      secure: kEisU/fcwa7tKolVPvk6cgUhU64S6NbkOAJg81KKSbXRODVeXRjOhA8nB4SSJ/YvzrRGJV12KAVrzyE6DNpswUy+Kk8XscskrPRdcvUGEvvBtNA+4myONEHAZZ55mHfEbcrPXSi+uYcO1D/lSUbfxD/2s5JVIGJYR9OPJJa92QyQ8NJF2CzDFpgVWUyPeny6RLkdav4M+vp69W6PPPig0Qw/GaKClK47BVaDh2H15EK0cHX/VvEdzm58BBfESArQ9S7YvAilu+yjF6uaDcpAnH/bHrLl+JEywFzrpT0xqyIl0LxDBhIK2LtYOk30bLZQlWe6gpWTopMuJC/qUtI6/4BYk9SVF+AUhF/J1JxmcStLxLmPMzGN7eVvhhWCzrVLLkkOcTowYXBp0XYB/vuCbQngh9xvyJSZzdIdGNMNBXD9VKxB04k0v5Z4F7vUccQm13hYlSMS8WjSW37UYTF/o04R8TLfhVFjWqxi+3SY9vBgRs3A1p6Z0HHdvdsnQycmiVK//rnaLMq1GFz4M5Z7C2HZz3snqpUK3ZR/M6slFhmG3OBpgtuICFUVI2gd/kMd3VjEYbAkV+OEb76hM+YW+R3cLf40th8pV9FcceMeZxIulfFvQzIWvPvLXgrtePj6Nkk7UsXd/Oy0ivF3b/iPfw+J/sc/KGfBSpp6yFndWdY=
    on_success: always
    on_failure: always
env:
  global:
  - MIX_ENV=prod
branches:
  only:
  - devel
jobs:
  include:
  - stage: test and build
    name: Build Docker container
    script: make staging_build
