language: elixir
git:
  depth: 1000
cache:
  directories:
  - _build
  - deps
services:
- docker
elixir:
- 1.6.6
otp_release:
- 21.0
notifications:
  slack:
    rooms:
      secure: CHxJFHIVP8P5CtIh0t5EQ25Jjs68g1pV3Uergr+c8pzxRd1jiyGjmqjZJCj8Lm65ctvbhSJrcKh6fKOGGn1BpqeFbTqtVkG9VgBN2Ob9iUvT3HBek/wAPd5o8GDnEAz/87ZsvTJVHzMVfZVgqEoeXpIX8C4SS+OdYue2VF2ZEfZNZpxQF6ffPnY5zTbj8bXjfZl56MYhsLD7GLjQO1ruIRdmrsoJTkp0jOr+VLgxVRmyNCL9PZwQ2MheTVX8bWlF3amMpoOLPQY8kjkENcduTjstU+Hbkcyf92YRw+iaxX5ynH2/5wQ2xgfpb6z/E7QSK41Nsh2hTEvly6paNrA4ikxKazlnqr+rD+xJaX8+Jiek9vj0UvWr/VHAj2a2bTnrp6imVC5t6DCMQCB43IztAoqeL5X1ZbfmE53x1r4dg9agGN0ocOurovplWb+9n3W22gW/Lx+OVL5Fw2imDq+pywmsYKRHWIzKaWYbAZbg83P+NRSqU/ofED8XOMyT7nnPWyDWJj7728es6r7RfCJO7mOQzOaMz6A/kLzvQ3S5AJs2TbpHwBPvDKIXvJQIkRzVY9UophDdSHdLSZsztdgMRxpyvseSbPmTVLSJhhDukNd/kNV1JFFH3YppKocnBbYPmbGJD7BFu9FBtgny2LHR7JBHAUYI2LSaaiZrDSBUjeI=
env:
  global:
  - MIX_ENV=prod
branches:
  only:
  - devel
jobs:
  include:
  - stage: test and build
    name: Build Docker container
    script: make staging_build
