language: elixir
git:
  depth: 1000
cache:
  directories:
  - _build
  - deps
services:
- docker
elixir:
- 1.6.6
otp_release:
- 21.0
notifications:
  email:
    recipients:
    - andr.savenkov@i.ua
    on_success: always
    on_failure: always
  slack:
    rooms:
      - secure: sM/GIJkBSWIxPu5vL22g5m5bf4AoNgeATYh6j3vsG88u4uHQy/NifMu3wwGXL+M1q4ZYkWUVIPx2p7P1Vy7WrvAl9oqXyBJ3732yO9fw06CatTTgd2u5EFQ5rY7S9lzwcy5vJfjFGiDZxarzRnMluKRaj/UExX8VkN3+6qsIhacYdYgb2Uarj+fflmKPYetr1lcy3sRya4MA3biBN/TYUhJEUiIZcpJJ5ZCf2xNeKRf2E3wSch4T+mPnyfPeGuODRCP8P2Z4qmLSQPHsGnBB2spe2b7Ff7vHiAfjpG+qlEs2+EDpxEQKhMotsZu+ovI809M4FoYot0WDifJBkGeUwjPXyPPYI7l2HxkxLXgskJ/GT2qAd9MF0ATOH21B38l/0jGqGlyZaI1BEgvb11dYEYcBrYJonY/NMYvQsmrowjc01CA2JO7q3GfWohoC7gbMa5EY3l5ZkvgIzXTFUUO1dEtJeGlBudl4TfvoUBac/QduIzF98uh9BpNuIevF69K4XAyg9vM630KFnDIen8/252oIDeyYbQ2jIvlW9iPRLHzT4BpvwwtTdPiF4URd9aHJE3lJh/ZUMSrAYNB5xiRNn6KGuF2guklofH0uXK158gKPAeBljWxirZlueVJbu20Kpz5ZAYu4hDRc6otNRhvQCrWt/Ou/LqC5OwtTcdKXKhw=
    on_success: always
    on_failure: always
env:
  global:
  - MIX_ENV=prod
branches:
  only:
  - devel
jobs:
  include:
  - stage: test and build
    name: Build Docker container
    script: make staging_build
